# Generated by Django 2.0.7 on 2018-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='jumbotron',
            field=models.ImageField(default='header-blog-posts.jpg', upload_to=''),
        ),
    ]
